# 路径定义
THIS_NODE_DATA = "@THIS_NODE_DATA@"
CONTEXT_FUNCTION = "@CONTEXT_FUNCTION@"
VFOR_DATA = "@VFOR_DATA@"
PAYLOADS_ID = "@PAYLOADS_ID@"
# 连接项定义，路径为[CONNECT_*, <VFNodeConnectionType>, <Handle Id>], 如果没有<Handle Id>则默认获取所有<Handle Id>
# TODO: 连接项定义的具体数据结构
CONNECT_DATA = "@CONNECT_DATA@"
CONNECT_DATA_HANDLE = "@CONNECT_DATA_HANDLE@"
CONNECT_DATA_TO_SELECT = "@CONNECT_DATA_TO_SELECT@"
# 类型定义
TYPE_VFOR = "@VFOR@"
TYPE_VALUE = "@VALUE@"
TYPE_VBIND = "@VBIND@"
TYPE_VMODEL = "@VMODEL@"
TYPE_CONDITION_COMPARE = "@CONDITION_COMPARE@"
TYPE_CONDITION_LOGICAL = "@CONDITION_LOGICAL@"
TYPE_CONDITION_DIRECT = "@CONDITION_DIRECT@"
TYPE_CONDITION_VBIND = "@CONDITION_VBIND@"
TYPE_CONDITION_VALUE = "@CONDITION_VALUE@"
