# 路径定义
THIS_NODE_DATA = "@THIS_NODE_DATA@"
CONTEXT_FUNCTION = "@CONTEXT_FUNCTION@"
VFOR_DATA = "@VFOR_DATA@"
NODE_CONFIG_DATA = "@NODE_CONFIG_DATA@"
PAYLOADS_ID = "@PAYLOADS_ID@"
CONTEXT_ARG = "@CONTEXT_ARG@"
# 专供FUNCTION_CONTEXT
GENERATE_UUID = "@GENERATE_UUID@"
# 连接项定义，路径为[CONNECT_*, <VFNodeConnectionType>, <Handle Id>], 如果没有<Handle Id>则默认获取所有<Handle Id>
# TODO: 连接项定义的具体数据结构
CONNECT_DATA = "@CONNECT_DATA@"
CONNECT_DATA_TO_SELECT = "@CONNECT_DATA_TO_SELECT@"
# 连接项的参数定义
CONNECT_ALL_DATA = "@CONNECT_ALL_DATA@"
CONNECT_CUR_NODE = "@CONNECT_CUR_NODE@"
CONNECT_PARENT_NODE = "@CONNECT_PARENT_NODE@"
CONNECT_CHILD_NODE = "@CONNECT_CHILD_NODE@"
CONNECT_PRE_NODE = "@CONNECT_PRE_NODE@"
CONNECT_NODE_LEVEL = "@CONNECT_NODE_LEVEL@"
CONNECT_HANDLE_LEVEL = "@CONNECT_HANDLE_LEVEL@"
CONNECT_VAR_LEVEL = "@CONNECT_VAR_LEVEL@"
# 类型定义
TYPE_VFOR = "@VFOR@"
TYPE_VALUE = "@VALUE@"
TYPE_VBIND = "@VBIND@"
TYPE_VMODEL = "@VMODEL@"
TYPE_CONDITION_COMPARE = "@CONDITION_COMPARE@"
TYPE_CONDITION_LOGICAL = "@CONDITION_LOGICAL@"
TYPE_CONDITION_DIRECT = "@CONDITION_DIRECT@"
TYPE_CONDITION_VBIND = "@CONDITION_VBIND@"
TYPE_CONDITION_VALUE = "@CONDITION_VALUE@"
