import { type Component } from 'vue'
import {
  // 通用组件
  NButton,
  NCard,
  NCollapse,
  NCollapseItem,
  NDivider,
  NDropdown,
  NEllipsis,
  NIcon,
  NTag,
  NH1,
  NH2,
  NH3,
  NH4,
  NH5,
  NH6,
  NText,
  NAutoComplete,
  // 数据录入组件
  NCascader,
  NColorPicker,
  NCheckbox,
  NCheckboxGroup,
  NDatePicker,
  NDynamicInput,
  NDynamicTags,
  // NForm,
  // NFormItem,
  NInput,
  NInputNumber,
  NMention,
  NRadio,
  NRadioButton,
  NRadioGroup,
  NRate,
  NSelect,
  NSlider,
  NSwitch,
  NTimePicker,
  NTransfer,
  NTreeSelect,
  // 数据展示组件
  NCalendar,
  NCountdown,
  NCode,
  NDataTable,
  NDescriptions,
  NDescriptionsItem,
  NEmpty,
  NEquation,
  NImage,
  NImageGroup,
  NList,
  NListItem,
  NLog,
  NNumberAnimation,
  NQrCode,
  NStatistic,
  NTable,
  NTime,
  NTimeline,
  NTimelineItem,
  NTree,
  NHighlight,
  // 导航组件
  NTab,
  // 反馈组件
  NMarquee,
  // 布局组件
  NFlex,
  NGrid,
  NGridItem,
  NRow,
  NCol,
  NSpace,
} from 'naive-ui'

export const DYNAMIC_COMPONENTS_MAP: Record<string, Component> = {
  NButton: NButton,
  NCard: NCard,
  NCollapse: NCollapse,
  NCollapseItem: NCollapseItem,
  NDivider: NDivider,
  NDropdown: NDropdown,
  NEllipsis: NEllipsis,
  NIcon: NIcon,
  NTag: NTag,
  NH1: NH1,
  NH2: NH2,
  NH3: NH3,
  NH4: NH4,
  NH5: NH5,
  NH6: NH6,
  NText: NText,
  NAutoComplete: NAutoComplete,
  NCascader: NCascader,
  NColorPicker: NColorPicker,
  NCheckbox: NCheckbox,
  NCheckboxGroup: NCheckboxGroup,
  NDatePicker: NDatePicker,
  NDynamicInput: NDynamicInput,
  NDynamicTags: NDynamicTags,
  // NForm: NForm,
  // NFormItem: NFormItem,
  NInput: NInput,
  NInputNumber: NInputNumber,
  NMention: NMention,
  NRadio: NRadio,
  NRadioButton: NRadioButton,
  NRadioGroup: NRadioGroup,
  NRate: NRate,
  NSelect: NSelect,
  NSlider: NSlider,
  NSwitch: NSwitch,
  NTimePicker: NTimePicker,
  NTransfer: NTransfer,
  NTreeSelect: NTreeSelect,
  NCalendar: NCalendar,
  NCountdown: NCountdown,
  NCode: NCode,
  NDataTable: NDataTable,
  NDescriptions: NDescriptions,
  NDescriptionsItem: NDescriptionsItem,
  NEmpty: NEmpty,
  NEquation: NEquation,
  NImage: NImage,
  NImageGroup: NImageGroup,
  NList: NList,
  NListItem: NListItem,
  NLog: NLog,
  NNumberAnimation: NNumberAnimation,
  NQrCode: NQrCode,
  NStatistic: NStatistic,
  NTable: NTable,
  NTime: NTime,
  NTimeline: NTimeline,
  NTimelineItem: NTimelineItem,
  NTree: NTree,
  NHighlight: NHighlight,
  NTab: NTab,
  NMarquee: NMarquee,
  NFlex: NFlex,
  // 存在问题，NGridItem无法二次封装导致失效
  // NGrid: NGrid,
  // NGridItem: NGridItem,
  // NaiveUI组件库不建议使用以下两个
  // NRow: NRow,
  // NCol: NCol,
  NSpace: NSpace,
}

import RefVarSelect from '@/components/panelctrls/editables/RefVarSelect.vue'
export const DYNAMIC_FA_COMPONENTS_MAP: Record<string, Component> = {
  RefVarSelect: RefVarSelect,
}

import { Add, Close, CreateOutline } from '@vicons/ionicons5'
export const DYNAMIC_ICONS_MAP: Record<string, Component> = {
  Add: Add,
  Close: Close,
  CreateOutline: CreateOutline,
}
